# Generated by Django 4.2.1 on 2023-07-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/', verbose_name='Изображение'),
        ),
    ]
