# Generated by Django 4.2.1 on 2023-06-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoefinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='colors',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='purchaselinks',
            options={'verbose_name': 'Ссылка на покупку', 'verbose_name_plural': 'Ссылки на покупку'},
        ),
        migrations.AlterModelOptions(
            name='shoecolors',
            options={'verbose_name': 'Цвет кроссовок', 'verbose_name_plural': 'Цвета кроссовок'},
        ),
        migrations.AlterModelOptions(
            name='shoemodels',
            options={'verbose_name': 'Модель обуви', 'verbose_name_plural': 'Модели обуви'},
        ),
        migrations.AlterModelOptions(
            name='shoestyles',
            options={'verbose_name': 'Стиль кроссовок', 'verbose_name_plural': 'Стили кроссовок'},
        ),
        migrations.AlterModelOptions(
            name='styles',
            options={'verbose_name': 'Стиль', 'verbose_name_plural': 'Стили'},
        ),
        migrations.RemoveField(
            model_name='shoestyles',
            name='shoe',
        ),
        migrations.RemoveField(
            model_name='shoestyles',
            name='style',
        ),
        migrations.AddField(
            model_name='shoestyles',
            name='shoe_models',
            field=models.ManyToManyField(to='shoefinder.shoemodels'),
        ),
        migrations.AddField(
            model_name='shoestyles',
            name='styles',
            field=models.ManyToManyField(to='shoefinder.styles'),
        ),
    ]
