# Generated by Django 4.2.1 on 2023-06-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoefinder', '0002_alter_brand_options_alter_colors_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoestyles',
            old_name='shoe_models',
            new_name='shoe',
        ),
        migrations.RenameField(
            model_name='shoestyles',
            old_name='styles',
            new_name='style',
        ),
    ]
