# Generated by Django 4.2.6 on 2023-11-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoefinder', '0003_rename_shoe_models_shoestyles_shoe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoemodels',
            name='color',
            field=models.ManyToManyField(to='shoefinder.colors'),
        ),
        migrations.AddField(
            model_name='shoemodels',
            name='style',
            field=models.ManyToManyField(to='shoefinder.styles'),
        ),
    ]
