# Generated by Django 4.2.6 on 2023-12-06 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoefinder', '0005_historicalcolors_historicalbrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название бренда'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='historicalbrand',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название бренда'),
        ),
        migrations.AlterField(
            model_name='historicalcolors',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='shoemodels',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoefinder.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='shoemodels',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Стиль'),
        ),
    ]
